# Generated by Django 5.1.4 on 2024-12-19 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_title", models.CharField(max_length=35)),
                ("price", models.IntegerField()),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 12, 19, 17, 28, 7, 900162)
                    ),
                ),
                (
                    "product_picture",
                    models.ImageField(upload_to="media/product/pictures/"),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "product_category",
                    models.CharField(
                        choices=[
                            ("Техника", "Техника"),
                            ("Машина", "Машина"),
                            ("Дом", "Дом"),
                            ("Парфюм", "Парфюм"),
                            ("Еда", "Еда"),
                            ("Одежда", "Одежда"),
                            ("Игрушка", "Игрушка"),
                            ("Другое", "Другое"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
