# Generated by Django 5.1.4 on 2024-12-19 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_productmodel_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 19, 17, 44, 44, 272246)
            ),
        ),
    ]
