# Generated by Django 5.1.4 on 2024-12-19 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_cartmodel_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartmodel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 19, 17, 33, 32, 108102)
            ),
        ),
    ]
