# Generated by Django 5.1.4 on 2024-12-19 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 19, 17, 32, 43, 512503)
            ),
        ),
    ]
