# Generated by Django 5.1.4 on 2024-12-19 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_ordermodel_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 19, 17, 34, 1, 578982)
            ),
        ),
    ]
